# Change these first
owner: damoun # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: damoun.live
    url: https://damoun.live
    __dangerous__body_down: "sorry"
    icon: https://www.twitch.tv/favicon.ico
    expectedStatusCodes:
      - 200
    assignees:
      - $OWNER
  - name: damien.plenard.me
    url: https://damien.plenard.me
    icon: https://damien.plenard.me/assets/images/favicon-32x32.png
    expectedStatusCodes:
      - 200
    assignees:
      - $OWNER
  - name: damoun.link
    url: https://damoun.link
    icon: https://assets.production.linktr.ee/ed6b702d6a6a2565cf6f9cb504fe58e3121ef6fe/favicon/favicon-32x32.png
    expectedStatusCodes:
      - 200
    assignees:
      - $OWNER
  - name: damoun.club
    url: https://damoun.club
    icon: https://assets-global.website-files.com/6257adef93867e50d84d30e2/62fddf0fde45a8baedcc7ee5_847541504914fd33810e70a0ea73177e%20(2)-1.png
    expectedStatusCodes:
      - 200
    __dangerous__body_down: "invite invalid"
    assignees:
      - $OWNER
  - name: status.damoun.cloud
    url: https://status.damoun.cloud
    icon: https://status.damoun.cloud/logo-192.png
    expectedStatusCodes:
      - 200
    assignees:
      - $OWNER
  - name: mc.damoun.games
    url: http://62.210.45.167:40001
    icon: https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/favicon.ico
    expectedStatusCodes:
      - 200
    assignees:
      - $OWNER
  - name: grafana.damoun.cloud
    url: https://grafana.damoun.cloud
    expectedStatusCodes:
      - 200
    assignees:
      - $OWNER
  - name: charts.damoun.dev
    url: https://charts.damoun.dev/index.yaml
    icon: https://helm.sh/img/favicon-152.png
    expectedStatusCodes:
      - 200
    assignees:
      - $OWNER

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.damoun.cloud
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  theme: night
  introTitle: "Explore My World in Real-Time, powered entirely by GitHub with Upptime."
  introMessage: Dive into my personal status page to track the heartbeat from my Grafana to gaming servers or websites. Experience real-time updates, ensuring you're always in sync with the performance of these key elements. It's your window into the seamless operation of my digital domain. Welcome to the pulse of my online presence!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Grafana
      href: https://grafana.damoun.cloud

user-agent: $OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
