# Change these first
owner: damoun # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: twitch.tv/dam0un
    url: https://www.twitch.tv/dam0un
    icon: https://www.twitch.tv/favicon.ico
    expectedStatusCodes:
      - 200
  - name: dam0un.live
    url: https://dam0un.live
    expectedStatusCodes:
      - 200
    assignees:
      - $OWNER
  - name: damien.plenard.me
    url: https://damien.plenard.me
    expectedStatusCodes:
      - 200
    assignees:
      - $OWNER
  - name: damoun.link
    url: https://damoun.link
    expectedStatusCodes:
      - 200
    assignees:
      - $OWNER
  - name: status.damoun.cloud
    url: https://status.damoun.cloud
    expectedStatusCodes:
      - 200
    assignees:
      - $OWNER

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.damoun.cloud
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  theme: night
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: $OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
